language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - CI="" npm run build
deploy:
  provider: s3
  access_key_id: AKIAI2F5574NFCQQBEMA
  secret_access_key:
    secure: us2k9jrKoMFkOneNlcAu2zCrZLm8Th8NXJjj6EG6svKsf1/VZc9LpUoep2d4OvbQnhwvope5GZtLFQ5GKlHklRMy1s/ouN+mPRBN0KrGAoMiXisRaGgzXQBb3S1bb+zgzyOVeHOIQigU/voYJkcQOoKHfAfqyXyr9/uyh6e1kcN69rFg35e16iOrRa5N+0Trh8JoAC3HNTjhrPm40q2P6ZG0Sc2Tj1RRWZ/QPY4IPFljj9PuB9i9LJyOw1WPIbeTbRv+zu1dmIlwaaMQa/ii/k2DVluSz7sQOrKAJ12xebBj1oqoiio5yO1owJ6zWCsTWtb/Q0bQMQyxzOXT/1eWCqjte5qmVe+tfLF90piBS+PEVP74DzC9JWZ36woJCRNypjB9O4ylQ+y+r38d5Zf6m36fJtoD5mEfgt+zmnd95BKKXv8VLMMe+Jo7/kgnHN/ZUoz9mniZlW/aX15TR/KtWT7K12IU9rVsQ27vOEg22Uz6foOii4zROwY3ERHFDsgCRDmieMA0sl7OnK+w20G3HbXik2dLliF3qj1SdauLdbbEf1HfOGJFa9lob00w3lNP1ZtNpKxvdJpVYQeYk59gQ2ZBwUXwcJZeoyCb4qMxeRN5mSBfJCVnahPWJUlNtKaA08wbXJnGjNGdYBe+09HaO6p9OVcfkrLVl2dFVrsIgIg=
  bucket: madapt
  acl: public_read
  local_dir: build
  skip_cleanup: true
  region: ap-southeast-2
  on:
    repo: disposedtrolley/madapt-react-frontend
    branch: master
